#!/usr/bin/env sh 
. "$(dirname -- "$0")/_/husky.sh"

npx commitlint --edit "$1" || {
  echo "Commit message does not follow the conventional commit format."
  echo "Please refer to the guidelines for writing commit messages."
  exit 1
}
echo "Commit message is valid."
exit 0